# Generated by Django 4.2.24 on 2025-09-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NeetCounsellingSeatAllotment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allotment_category", models.CharField(max_length=255)),
                ("allotment_year", models.PositiveIntegerField()),
                ("rank_no", models.PositiveIntegerField()),
                ("allotted_quota", models.CharField(max_length=255)),
                ("allotted_institute", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("qualifying_group_or_course", models.CharField(max_length=255)),
                ("speciality", models.CharField(max_length=255)),
                ("allotted_category", models.CharField(max_length=255)),
                ("candidate_category", models.CharField(max_length=255)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "neet_counselling_seat_allotment",
            },
        ),
        migrations.CreateModel(
            name="NeetCounsellingSeatAllotmentTracker",
            fields=[
                ("seqno", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("rank_no", models.IntegerField(blank=True, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "allotment_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "qualifying_group_or_course",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "NEET_COUNSELLING_SEAT_ALLOTMENT_TRACKER",
            },
        ),
    ]
