# Generated by Django 4.2.24 on 2025-09-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CounsellingSeatAllotmentTracker",
            fields=[
                ("seqno", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("rank_no", models.IntegerField(blank=True, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "allotment_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "qualifying_group_or_course",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "COUNSELLING_SEAT_ALLOTMENT_TRACKER",
            },
        ),
    ]
