# Generated by Django 4.2.24 on 2025-09-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NeetCounsellingSeatAllotment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allotment_category", models.CharField(max_length=255)),
                ("allotment_year", models.PositiveIntegerField()),
                ("rank_no", models.PositiveIntegerField()),
                ("allotted_quota", models.CharField(max_length=255)),
                ("allotted_institute", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("qualifying_group_or_course", models.CharField(max_length=255)),
                ("speciality", models.CharField(max_length=255)),
                ("allotted_category", models.CharField(max_length=255)),
                ("candidate_category", models.CharField(max_length=255)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "neet_counselling_seat_allotment",
            },
        ),
    ]
