# Generated by Django 4.2.24 on 2025-09-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_name", models.CharField(max_length=255)),
                ("category_type", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "group_category_dropdown",
            },
        ),
    ]
