# Generated by Django 4.2.24 on 2025-09-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_neetcounsellingseatallotment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="neetcounsellingseatallotment",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
